openapi: 3.1.0
info:
  contact:
    email: claudio.fontana@suse.com
  description: This is a simple virtualization API for a KVM Cluster
  title: virtx
  version: 0.0.1
externalDocs:
  description: Find out more about the virtx project
  url: https://jira.suse.com/secure/Dashboard.jspa?selectPageId=67030
servers:
- url: https://example.org/api/v3
tags:
- description: Everything about Virtual Machines
  name: vm
- description: Everything about VM Resources
  name: vm_res
- description: Everything about Hosts
  name: host
- description: Everything about the Cluster
  name: cluster
paths:
  /vms:
    get:
      operationId: vm_list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vm_list_options'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_list'
          description: List available
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "422":
          description: Invalid Fields or Values
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Get the list of VMs in the cluster, optionally filtered (AND)"
      tags:
      - vm
    post:
      operationId: vm_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vm_create_options'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid'
          description: Created
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "422":
          description: Invalid Fields or Values
        "429":
          description: Compute Resource limits exceeded
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
        "507":
          description: Storage Insufficient
      summary: "Create a new VM, optionally on a specific host. Will return the new\
        \ uuid on success."
      tags:
      - vm
  /vms/{uuid}:
    delete:
      operationId: vm_delete
      parameters:
      - $ref: '#/components/parameters/uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vm_delete_options'
      responses:
        "204":
          description: Deleted
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "422":
          description: Invalid Fields or Values
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Deletes a powered-off VM, optionally deleting storage disks"
      tags:
      - vm
    get:
      operationId: vm_get
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vmdef'
          description: Found
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Get VM definition by uuid
      tags:
      - vm
    parameters:
    - $ref: '#/components/parameters/uuid'
    put:
      operationId: vm_update
      parameters:
      - $ref: '#/components/parameters/uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vmdef'
        required: true
      responses:
        "204":
          description: Updated
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "422":
          description: Invalid Fields or Values
        "429":
          description: Compute Resource limits exceeded
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
        "507":
          description: Storage Insufficient
      summary: Update an existing VM definition; the VM must be powered off.
      tags:
      - vm
  /vms/{uuid}/runstate:
    get:
      operationId: vm_get_runinfo
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vmruninfo'
          description: Found
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Get VM runstate
      tags:
      - vm
    parameters:
    - $ref: '#/components/parameters/uuid'
  /vms/{uuid}/runstate/start:
    parameters:
    - $ref: '#/components/parameters/uuid'
    post:
      operationId: vm_start
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Started
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Start a powered off VM, transitioning to running state"
      tags:
      - vm
  /vms/{uuid}/runstate/pause:
    delete:
      operationId: vm_resume
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Unpaused
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Resume a paused VM, transitioning to running state"
      tags:
      - vm
    parameters:
    - $ref: '#/components/parameters/uuid'
    post:
      operationId: vm_pause
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Paused
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Pause a running VM, transitioning to paused state"
      tags:
      - vm
  /vms/{uuid}/runstate/shutdown:
    parameters:
    - $ref: '#/components/parameters/uuid'
    post:
      operationId: vm_shutdown
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Powered off
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "Signal a VM to shut down gracefully, transitioning to poweroff state"
      tags:
      - vm
  /vms/{uuid}/runstate/poweroff:
    parameters:
    - $ref: '#/components/parameters/uuid'
    post:
      operationId: vm_poweroff
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Powered off
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Poweroff a VM forcefully. Not recommended in most cases.
      tags:
      - vm
  /vms/{uuid}/runstate/migration:
    delete:
      operationId: vm_migrate_cancel
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "204":
          description: Migration Canceled
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Cancel the current migration
      tags:
      - vm
    get:
      operationId: vm_migrate_get
      parameters:
      - $ref: '#/components/parameters/uuid'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_migrate_info'
          description: Migration Info available
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Get the status information of the current migration
      tags:
      - vm
    parameters:
    - $ref: '#/components/parameters/uuid'
    post:
      operationId: vm_migrate
      parameters:
      - $ref: '#/components/parameters/uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vm_migrate_options'
      responses:
        "202":
          description: Migration Started
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "404":
          description: Not Found
        "422":
          description: Invalid Fields or Values
        "429":
          description: Compute Resource limits exceeded
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
        "507":
          description: Storage Insufficient
      summary: Initiate a migration (cold or live) of a VM to another compute host
      tags:
      - vm
  /cluster:
    get:
      operationId: cluster_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cluster'
          description: Cluster Info available
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: Get the cluster information
      tags:
      - cluster
  /hosts:
    get:
      operationId: host_list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/host_list_options'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/host_list'
          description: List available
        "400":
          description: Generic Client Error
        "401":
          description: Unauthorized (need to login)
        "403":
          description: Forbidden (not allowed)
        "422":
          description: Invalid Fields or Values
        "500":
          description: Generic Server Error
        "501":
          description: Not implemented yet
        "503":
          description: Service Unavailable
      summary: "List all hosts, optionally filtering (AND)"
      tags:
      - host
components:
  parameters:
    uuid:
      explode: false
      in: path
      name: uuid
      required: true
      schema:
        $ref: '#/components/schemas/uuid'
      style: simple
  responses:
    "400":
      description: Generic Client Error
    "401":
      description: Unauthorized (need to login)
    "403":
      description: Forbidden (not allowed)
    "404":
      description: Not Found
    "422":
      description: Invalid Fields or Values
    "429":
      description: Compute Resource limits exceeded
    "500":
      description: Generic Server Error
    "501":
      description: Not implemented yet
    "503":
      description: Service Unavailable
    "507":
      description: Storage Insufficient
  schemas:
    uuid:
      description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
      example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
      format: uuid
      maxLength: 36
      minLength: 36
      type: string
    page:
      description: "Paging information, to limit the size of results returned at once.\
        \ The page index (starting with 0) and the page size (number of items per\
        \ page) are used on the server side to prepare and return the results."
      example:
        size: 18
        index: 0
      properties:
        index:
          example: 0
          format: int32
          maximum: 1999
          minimum: 0
          type: integer
        size:
          format: int32
          maximum: 100
          minimum: 5
          type: integer
    vm_create_options:
      properties:
        vmdef:
          $ref: '#/components/schemas/vmdef'
        host:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
      required:
      - vmdef
    vm_list_options:
      properties:
        filter:
          $ref: '#/components/schemas/vm_list_fields'
        page:
          $ref: '#/components/schemas/page'
    vm_list:
      example:
        items:
        - uuid: 477e5eec-5168-4326-aa9f-2a56133a9730
          fields:
            name: guest1
            host: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
            vmrunstate: running
            vlanid: 95
            custom:
            - name: CID
              value: "1217"
        - uuid: aca18300-82b4-4d6b-8550-c903624cde2f
          fields:
            name: guest2
            host: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
            vmrunstate: running
            vlanid: 95
            custom:
            - name: CID
              value: "1217"
        page:
          index: 0
          size: 5
        total: 2
      properties:
        items:
          items:
            $ref: '#/components/schemas/vm_list_item'
          maxItems: 100
          type: array
        page:
          $ref: '#/components/schemas/page'
        total:
          description: total number of vm items in all the result pages
          example: 125
          format: int32
          maximum: 10000
          minimum: 0
          type: integer
    vm_list_item:
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        fields:
          $ref: '#/components/schemas/vm_list_fields'
    vm_list_fields:
      properties:
        name:
          maxLength: 64
          type: string
        host:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        vmrunstate:
          $ref: '#/components/schemas/vmrunstate'
        vlanid:
          description: vlanid for all traffic from/to this VM. 0 = automatically assign
          example: 95
          maximum: 2047
          minimum: 0
          type: integer
        custom:
          description: Custom Fields
          items:
            $ref: '#/components/schemas/custom_field'
          maxItems: 2
          type: array
    vm_delete_options:
      properties:
        delete_storage:
          description: "if true, delete also the associated storage (disks)"
          example: false
          type: boolean
    vm_migrate_options:
      properties:
        host:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
    vm_migrate_info:
      example:
        progress:
          total: 8192
          transferred: 5120
          rate: 240.1
          remaining: 3072
        state: active
      properties:
        state:
          description: the status of the migration
          enum:
          - none
          - setup
          - cancelling
          - cancelled
          - active
          - pre-switchover
          - device
          - wait-unplug
          - completed
          - failed
          example: active
          maxLength: 64
          type: string
        progress:
          $ref: '#/components/schemas/vm_migrate_info_progress'
    vm:
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        vmdef:
          $ref: '#/components/schemas/vmdef'
        runstate:
          $ref: '#/components/schemas/vmruninfo'
    vmdef:
      example:
        sap: true
        memory:
          total: 8192
        disks:
        - path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          bus: scsi
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          device: disk
        - path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          bus: scsi
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          device: disk
        - path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          bus: scsi
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          device: disk
        - path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          bus: scsi
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          device: disk
        - path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          bus: scsi
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          device: disk
        vlanid: 95
        nets:
        - name: default
          model: virtio-net
          type: libvirt
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          mac: 52:54:00:8c:25:ef
        - name: default
          model: virtio-net
          type: libvirt
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          mac: 52:54:00:8c:25:ef
        - name: default
          model: virtio-net
          type: libvirt
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          mac: 52:54:00:8c:25:ef
        - name: default
          model: virtio-net
          type: libvirt
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          mac: 52:54:00:8c:25:ef
        - name: default
          model: virtio-net
          type: libvirt
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          mac: 52:54:00:8c:25:ef
        custom:
        - name: CID
          value: "1217"
        - name: CID
          value: "1217"
        cpudef:
          cores: 8
          threads: 1
          model: Cascadelake-Server-noTSX
          sockets: 1
        smbios: host
        genid: 43dc0cf8-809b-4adb-9bea-a9abb5f3d90e
        displayname: SLES 12sp5 sap-guest123
        name: sap-guest123
        firmware: bios
        watchdog_action: none
      properties:
        name:
          example: sap-guest123
          maxLength: 64
          type: string
        displayname:
          example: SLES 12sp5 sap-guest123
          maxLength: 256
          type: string
        vlanid:
          description: vlanid for all traffic from/to this VM. 0 = automatically assign
          example: 95
          maximum: 2047
          minimum: 0
          type: integer
        watchdog_action:
          enum:
          - none
          - reset
          example: none
          maxLength: 64
          type: string
        firmware:
          enum:
          - bios
          - uefi
          example: bios
          maxLength: 64
          type: string
        genid:
          description: VM generation ID. Use special value "auto" to autogenerate
          example: 43dc0cf8-809b-4adb-9bea-a9abb5f3d90e
          format: genid
          maxLength: 36
          type: string
        smbios:
          description: where the Virtual SMBIOS should get information from
          enum:
          - emulate
          - host
          example: host
          maxLength: 64
          type: string
        sap:
          description: enable SAP-specific VM advanced configuration
          example: true
          type: boolean
        custom:
          description: Custom Fields
          items:
            $ref: '#/components/schemas/custom_field'
          maxItems: 2
          type: array
        disks:
          description: disks attached to the VM
          items:
            $ref: '#/components/schemas/disk'
          maxItems: 120
          type: array
        nets:
          description: networks and bridges attached to the VM
          items:
            $ref: '#/components/schemas/net'
          maxItems: 10
          type: array
        cpudef:
          $ref: '#/components/schemas/cpudef'
        memory:
          $ref: '#/components/schemas/vmdef_memory'
      required:
      - name
    cpudef:
      example:
        cores: 8
        threads: 1
        model: Cascadelake-Server-noTSX
        sockets: 1
      properties:
        model:
          description: libvirt cpu model
          example: Cascadelake-Server-noTSX
          maxLength: 64
          type: string
        sockets:
          description: number of sockets (NUMA)
          example: 1
          format: int32
          maximum: 2048
          minimum: 1
          type: integer
        cores:
          description: number of cores per socket
          example: 8
          format: int32
          maximum: 256
          minimum: 1
          type: integer
        threads:
          description: number of threads per core
          example: 1
          format: int32
          maximum: 32
          minimum: 1
          type: integer
    disk:
      example:
        path: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
        bus: scsi
        uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        device: disk
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        device:
          enum:
          - disk
          - cdrom
          - floppy
          maxLength: 64
          type: string
        path:
          example: /vmstorage/volumes/datastore1/customer1/guest123/guest123.qcow2
          maxLength: 4096
          type: string
        bus:
          enum:
          - scsi
          - sata
          - ide
          - virtio
          maxLength: 64
          type: string
    net:
      example:
        name: default
        model: virtio-net
        type: libvirt
        uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        mac: 52:54:00:8c:25:ef
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        type:
          enum:
          - libvirt
          - bridge
          example: libvirt
          maxLength: 64
          type: string
        name:
          example: default
          maxLength: 64
          type: string
        model:
          enum:
          - virtio-net
          - e1000e
          - e1000
          maxLength: 64
          type: string
        mac:
          example: 52:54:00:8c:25:ef
          format: mac
          maxLength: 17
          minLength: 17
          type: string
    vlanid:
      description: vlanid for all traffic from/to this VM. 0 = automatically assign
      example: 95
      maximum: 2047
      minimum: 0
      type: integer
    custom_fields:
      description: Custom Fields
      items:
        $ref: '#/components/schemas/custom_field'
      maxItems: 2
      type: array
    custom_field:
      description: Custom Field
      example:
        name: CID
        value: "1217"
      properties:
        name:
          maxLength: 64
          type: string
        value:
          maxLength: 64
          type: string
    vmruninfo:
      example:
        host: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        state: poweroff
      properties:
        state:
          $ref: '#/components/schemas/vmrunstate'
        host:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
    vmrunstate:
      description: The run state of the VM
      enum:
      - poweroff
      - running
      - paused
      - migrating
      - terminating
      - pmsuspended
      - crashed
      maxLength: 64
      type: string
    host_list_options:
      properties:
        filter:
          $ref: '#/components/schemas/host_list_fields'
        page:
          $ref: '#/components/schemas/page'
    host:
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        hostdef:
          $ref: '#/components/schemas/hostdef'
        hoststate:
          $ref: '#/components/schemas/hoststate'
        hostresources:
          $ref: '#/components/schemas/hostresources'
    hostdef:
      properties:
        name:
          maxLength: 64
          type: string
        cpuarch:
          $ref: '#/components/schemas/cpuarch'
        cpudef:
          $ref: '#/components/schemas/cpudef'
        tsc_freq:
          description: TSC frequency in Hz
          format: int64
          type: integer
        sysinfo_bios:
          maxLength: 64
          type: string
    cpuarch:
      example:
        vendor: 6
        arch: 0
      properties:
        arch:
          description: the CPU base architecture
          nullable: true
          type: integer
        vendor:
          description: "vendor as per libvirt definition, x86_vendors.xml, arm_vendors.xml"
          nullable: true
          type: integer
    hoststate:
      enum:
      - alive
      - left
      - failed
      maxLength: 64
      type: string
    hostresources:
      example:
        memory:
          used_virtx: 400
          total: 16000
          used_os: 1000
          reserved_virtx: 500
          reserved_vms: 12000
          reserved: 14500
          used_vms: 8000
          used: 9400
          free: 6600
          reserved_os: 2000
          available_vms: 5500
        mhz:
          used_virtx: 400
          total: 16000
          used_os: 1000
          reserved_virtx: 500
          reserved_vms: 12000
          reserved: 14500
          used_vms: 8000
          used: 9400
          free: 6600
          reserved_os: 2000
          available_vms: 5500
      properties:
        memory:
          $ref: '#/components/schemas/hostresource'
        mhz:
          $ref: '#/components/schemas/hostresource'
    hostresource:
      example:
        used_virtx: 400
        total: 16000
        used_os: 1000
        reserved_virtx: 500
        reserved_vms: 12000
        reserved: 14500
        used_vms: 8000
        used: 9400
        free: 6600
        reserved_os: 2000
        available_vms: 5500
      properties:
        total:
          description: total available on the host
          example: 16000
          format: int64
          type: integer
        reserved_os:
          description: "reserved for linux and other system processes, os tools"
          example: 2000
          format: int64
          type: integer
        used_os:
          description: "used for linux and other system processes, os tools"
          example: 1000
          format: int64
          type: integer
        reserved_virtx:
          description: "reserved specifically by virtx api, services"
          example: 500
          format: int64
          type: integer
        used_virtx:
          description: "used for virtx api, services"
          example: 400
          format: int64
          type: integer
        reserved_vms:
          description: reserved for running the guests currently on this host
          example: 12000
          format: int64
          type: integer
        used_vms:
          description: used for running vm guests
          example: 8000
          format: int64
          type: integer
        used:
          description: used_os + used_virtx + used_vms
          example: 9400
          format: int64
          type: integer
        free:
          description: total - used
          example: 6600
          format: int64
          type: integer
        reserved:
          description: reserved_os + reserved_virtx + reserved_vms
          example: 14500
          format: int64
          type: integer
        available_vms:
          description: available for other VMs (total - reserved)
          example: 5500
          format: int64
          type: integer
    host_list:
      example:
        total: 1
        page:
          size: 18
          index: 0
        items:
        - fields:
            hoststate: alive
            name: myhost.example.org
            cpuarch:
              vendor: 6
              arch: 0
            cpudef:
              cores: 8
              threads: 1
              model: Cascadelake-Server-noTSX
              sockets: 1
            memory_available_vms: 5500
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        - fields:
            hoststate: alive
            name: myhost.example.org
            cpuarch:
              vendor: 6
              arch: 0
            cpudef:
              cores: 8
              threads: 1
              model: Cascadelake-Server-noTSX
              sockets: 1
            memory_available_vms: 5500
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        - fields:
            hoststate: alive
            name: myhost.example.org
            cpuarch:
              vendor: 6
              arch: 0
            cpudef:
              cores: 8
              threads: 1
              model: Cascadelake-Server-noTSX
              sockets: 1
            memory_available_vms: 5500
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        - fields:
            hoststate: alive
            name: myhost.example.org
            cpuarch:
              vendor: 6
              arch: 0
            cpudef:
              cores: 8
              threads: 1
              model: Cascadelake-Server-noTSX
              sockets: 1
            memory_available_vms: 5500
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
        - fields:
            hoststate: alive
            name: myhost.example.org
            cpuarch:
              vendor: 6
              arch: 0
            cpudef:
              cores: 8
              threads: 1
              model: Cascadelake-Server-noTSX
              sockets: 1
            memory_available_vms: 5500
          uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
      properties:
        items:
          items:
            $ref: '#/components/schemas/host_list_item'
          maxItems: 100
          type: array
        page:
          $ref: '#/components/schemas/page'
        total:
          description: total number of host items in all the result pages
          example: 1
          format: int32
          maximum: 100
          minimum: 0
          type: integer
    host_list_item:
      example:
        fields:
          hoststate: alive
          name: myhost.example.org
          cpuarch:
            vendor: 6
            arch: 0
          cpudef:
            cores: 8
            threads: 1
            model: Cascadelake-Server-noTSX
            sockets: 1
          memory_available_vms: 5500
        uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        fields:
          $ref: '#/components/schemas/host_list_fields'
    host_list_fields:
      example:
        hoststate: alive
        name: myhost.example.org
        cpuarch:
          vendor: 6
          arch: 0
        cpudef:
          cores: 8
          threads: 1
          model: Cascadelake-Server-noTSX
          sockets: 1
        memory_available_vms: 5500
      properties:
        name:
          example: myhost.example.org
          maxLength: 64
          type: string
        cpuarch:
          $ref: '#/components/schemas/cpuarch'
        cpudef:
          $ref: '#/components/schemas/cpudef'
        hoststate:
          $ref: '#/components/schemas/hoststate'
        memory_available_vms:
          description: available for other VMs (total - reserved)
          example: 5500
          format: int64
          type: integer
    cluster:
      example:
        name: name
        resources:
          memory:
            used_virtx: 400
            total: 16000
            used_os: 1000
            reserved_virtx: 500
            reserved_vms: 12000
            reserved: 14500
            used_vms: 8000
            used: 9400
            free: 6600
            reserved_os: 2000
            available_vms: 5500
          mhz:
            used_virtx: 400
            total: 16000
            used_os: 1000
            reserved_virtx: 500
            reserved_vms: 12000
            reserved: 14500
            used_vms: 8000
            used: 9400
            free: 6600
            reserved_os: 2000
            available_vms: 5500
        uuid: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
      properties:
        uuid:
          description: "Unique Identifier for VMs, Hosts, Cluster, RFC 4122"
          example: 3e3fce45-4f53-4fa7-bb32-11f34168b82b
          format: uuid
          maxLength: 36
          minLength: 36
          type: string
        name:
          maxLength: 64
          type: string
        resources:
          $ref: '#/components/schemas/hostresources'
    vm_migrate_info_progress:
      example:
        total: 8192
        transferred: 5120
        rate: 240.1
        remaining: 3072
      properties:
        total:
          description: MiB of RAM to be trasferred
          example: 8192
          format: int64
          type: integer
        transferred:
          description: MiB already transferred to the migration target
          example: 5120
          format: int64
          type: integer
        remaining:
          description: MiB remaining to be transferred to the target
          example: 3072
          format: int64
          type: integer
        rate:
          description: MiB per second. Only available for "active" and "completed"
          example: 240.1
          format: float
          type: number
    vmdef_memory:
      example:
        total: 8192
      properties:
        total:
          description: total memory to reserve for the guest in MiB
          example: 8192
          format: int64
          minimum: 4096
          type: integer
  securitySchemes:
    cluster_auth:
      flows:
        implicit:
          authorizationUrl: https://example.org/oauth/authorize
          scopes:
            write:vms: modify VMs
            read:vms: read VMs
      type: oauth2
    api_key:
      in: header
      name: api_key
      type: apiKey
